ubottu/factoids/urls.py
from django.urls import path
from .views import FactList
from . import views

urlpatterns = [
    path('', views.list_facts, name='facts-list'),
    path('api/citytime/<str:city_name>/', views.city_time, name='citytime'),
    path('api/facts/', FactList.as_view(), name='fact-list'),  # For listing all facts
    path('api/facts/<int:id>/', FactList.as_view(), name='fact-detail-by-id'),  # For fetching by id
    path('api/facts/<slug:name>/', FactList.as_view(), name='fact-detail-by-name'),  # For fetching by name
]

ubottu/ubottu/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path("factoids/", include("factoids.urls")),
    path("bugtracker/", include("bugtracker.urls")),
    path("launchpad/", include("launchpad.urls")),
    path("admin/", admin.site.urls),
    path('', lambda request: redirect('factoids/', permanent=False)),  # Redirect from root to 'factoids'
]

ubottu/factoids/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Define Author model
class Author(models.Model):
    name = models.CharField(max_length=64)

def get_sentinel_author():
    # This assumes 'Author' model is already defined as shown above
    return Author.objects.get_or_create(name='deleted')[0]
class Fact(models.Model):
    name = models.CharField(max_length=32)
    value = models.TextField()
    FTYPE_CHOICES = (
        ("REPLY", "Reply"),
        ("ALIAS", "Alias")
    )
    ftype = models.CharField(
        max_length=32,
        choices=FTYPE_CHOICES,
        default="REPLY"
    )
    
    id = models.BigAutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    room = models.CharField(null=True, default=None, max_length=128, blank=True)
    create_date = models.DateTimeField("date published", default=timezone.now)
    change_date = models.DateTimeField("date changed", default=timezone.now)
    popularity = models.IntegerField(default=0)
    def __str__(self):
        return self.name

    def was_published_recently(self):
        return self.create_date >= timezone.now() - datetime.timedelta(days=7)

ubottu/factoids/forms.py
from django.forms import ModelForm, Textarea
from .models import Fact
class FactForm(ModelForm):
    class Meta:
        model = Fact
        fields = '__all__'
        widgets = {
                'value': Textarea(attrs={'cols': 60, 'rows': 10}),
        }

ubottu/factoids/views.py
from django.http import HttpResponse, Http404
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from rest_framework.response import Response
from .models import Fact
from .serializers import FactSerializer
from django.shortcuts import render
from geopy.geocoders import Nominatim
from timezonefinder import TimezoneFinder
from datetime import datetime
from rest_framework import status
import pytz
import json

def index(request):
    return HttpResponse("Hello, world. You're at the factoids index.")

@api_view(['GET'])
def city_time(request, city_name):
    try:
        if city_name.upper() == 'UTC':
            city_name = 'UTC'
            datetime_obj = datetime.now(pytz.utc)
            local_time = datetime_obj.strftime('%A, %d %B %Y, %H:%M')
            data = {'location': '', 'city': city_name, 'local_time': local_time, 'utc_offset': 'UTC+00:00'}
            return Response(data)
        else:
            geolocator = Nominatim(user_agent="Ubottu", timeout=10)
            location = geolocator.geocode(city_name, exactly_one=True, language='en')
            if location is None:
                # If the location wasn't found, return an appropriate response
                return Response({'error': 'Location not found'}, status=status.HTTP_404_NOT_FOUND)

            tf = TimezoneFinder()
            timezone_str = tf.timezone_at(lat=location.latitude, lng=location.longitude)  # Get the timezone name
            
            if timezone_str is None:
                # If the timezone wasn't found, return an appropriate response
                return Response({'error': 'Timezone not found for the given location'}, status=status.HTTP_404_NOT_FOUND)
        
            timezone = pytz.timezone(timezone_str)

        datetime_obj = datetime.now(timezone)
        local_time = datetime_obj.strftime('%A, %d %B %Y, %H:%M')
        city_name = str(location).split(',')[0]
        utc_offset = datetime_obj.strftime('%z')
        formatted_offset = f"UTC{utc_offset[:3]}:{utc_offset[3:]}"
        data = {'location': str(location), 'city': city_name, 'local_time': local_time, 'utc_offset': formatted_offset}
        return Response(data)
    except Exception as e:
        # Log the exception if needed
        print(f"Error processing request for city {city_name}: {str(e)}")
        # Return a JSON response indicating an error occurred
        # Returning False directly is not recommended for API responses
        return Response({'error': 'An error occurred processing your request'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


def list_facts(request):
    #facts = Fact.objects.all()
    sort_by = request.GET.get('sort', 'name')  # Default sort by 'name'
    allowed_sorts = ['name', 'ftype', 'popularity']
    if sort_by not in allowed_sorts:
        sort_by = 'name'  # Fallback to a safe default
    if sort_by == 'popularity':
        facts = Fact.objects.order_by('-popularity', 'name')
    else:
        facts = Fact.objects.order_by(sort_by)
    return render(request, 'factoids/list_facts.html', {'facts': facts})

class FactList(APIView):
    """
    List all Fact items or retrieve a single Fact item by name or id.
    """
    def get(self, request, *args, **kwargs):
        # Check if an 'id' parameter is provided in the URL.
        fact_id = kwargs.get('id')
        # Check if a 'name' parameter is provided in the URL.
        name = kwargs.get('name')
        
        if fact_id:
            # Fetching the Fact item by id.
            try:
                fact = Fact.objects.get(id=fact_id)
            except Fact.DoesNotExist:
                raise Http404("Fact not found")
        elif name:
            # Fetching the Fact item by name.
            try:
                fact = Fact.objects.get(name=name)
                fact.popularity += 1  # Increment popularity
                fact.save(update_fields=['popularity'])  # Save the change
            except Fact.DoesNotExist:
                raise Http404("Fact not found")
        else:
            # If neither 'id' nor 'name' is provided, you might want to list all facts
            # or handle the situation differently (e.g., return an error response).
            facts = Fact.objects.all()
            serializer = FactSerializer(facts, many=True)
            return Response(serializer.data)

        # Serializing the retrieved Fact item.
        serializer = FactSerializer(fact)
        return Response(serializer.data)

ubottu/factoids/templates/factoids/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.7.2/font/bootstrap-icons.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'factoids/css/styles.css' %}">
    <link rel="icon" href="{% static 'factoids/images/favicon.ico' %}" type="image/x-icon">
    <title>{% block title %}Factoids{% endblock %}</title>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
          const themeToggleButton = document.getElementById('theme-toggle');
          const currentTheme = localStorage.getItem('theme') || 'light';
        
          if (currentTheme === 'dark') {
            document.body.classList.add('dark-theme');
            themeToggleButton.classList.add('active');
          }
        
          themeToggleButton.addEventListener('click', function() {
            document.body.classList.toggle('dark-theme');
            themeToggleButton.classList.toggle('active');
            localStorage.setItem('theme', document.body.classList.contains('dark-theme') ? 'dark' : 'light');
          });
        });
    </script> 
</head>
<body>
    <header>
        <h1>Factoids</h1>
        <!-- Navigation, etc. -->
    </header>
    <div class="theme-toggle-container">
        <button id="theme-toggle" class="btn toggle-switch">
            <span class="switch"></span>
        </button>
        <span class="toggle-description">Dark Mode</span>
    </div>
    <main>
        {% block content %}
        {% endblock content %}
    </main>

    <footer>
        <!-- Footer content -->
    </footer>
</body>
</html>

ubottu/factoids/templates/factoids/list_facts.html
{% extends "factoids/base.html" %}
{% block content %}
<script>
    $(document).ready(function() {
        $('.expandable').click(function() {
            $(this).toggleClass('expanded');
            if ($(this).hasClass('expanded')) {
                $(this).css({'max-height': 'none', 'white-space': 'normal'});
            } else {
                $(this).css({'max-height': '20px', 'white-space': 'nowrap'});
            }
        });
    });
</script>
<div class="container mt-3"> 
    <h2>Facts List</h2>
    <div class="table-responsive"> <!-- Make table responsive -->
        <table class="table table-striped table-hover"> <!-- Add Bootstrap classes for styling -->
            <thead class="thead-dark"> <!-- Use a darker theme for the table header -->
                <tr>
                    <th><a href="?sort=name">Name</a></th>
                    <th>Value</th>
                    <th>Type</th>
                    <th>Room</th>
                    <th>Author</th>
                    <th><a href="?sort=popularity">Popularity</a></th>
                </tr>
            </thead>
            <tbody>
                {% for fact in facts %}
                <tr>
                    <td>{{ fact.name }}</td>
                    <td class="expandable">{{ fact.value }}</td>
                    <td>{{ fact.get_ftype_display }}</td>
                    <td>{% if fact.room %}{{ fact.room }}{% else %}all{% endif %}</td>
                    <td>{% if fact.author %}{{ fact.author.username }}{% else %}N/A{% endif %}</td>
                    <td>{{ fact.popularity }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="alert alert-info d-flex align-items-center" role="alert">
        <i class="bi bi-info-circle-fill me-2"></i>
        <div>
            You can get <a href="/factoids/api/facts/">all</a> or <a href="/factoids/api/facts/">single</a> facts via the API.
        </div>
    </div>
</div>
{% endblock %}